#!/bin/sh
#
# Generate a .mk for some .cxx file that should be made into an executable
#
# Usage: add-prog.sh [filename.cxx]
#

cxxfile=$1
basname=${cxxfile%.cxx}
sulname=${basname##*/}

if [ -f ${basname}.cxx ]; then
   mkfile=${basname}.mk
   if [ -f $mkfile ]; then
      echo "Error: $mkfile already exists. Remove $mkfile before regenerating."
   else
      cat > $mkfile <<EOF
###
# File generated by "add-prog.sh ${cxxfile}".
#
# \$Id\$
###

# List here objects that should be explicitly built into the executable.
# NOTE: DO NOT include "${sulname}.o" in this list.
${sulname}OBJS := \\
	

# List here library paths (-L) and libraries (-l) that the executable
# should be linked with.
${sulname}LINK := \\
	\`root-config --libs\` \\
	\`build/sns-libs.sh\` \\
	
# By default the general ROOT libraries and SnowShovel libraries are inlcuded.
# Remove these if they are not needed.


################################################################################
# DO NOT EDIT BELOW
################################################################################
bin/${sulname}.\$(EXEEXT):: prog/${sulname}.o \$(${sulname}OBJS) prog/${sulname}.mk
	@\$(MAKEEXE) \$(MAKELIB) \$(PLATFORM) \$(LD) "\$(LDFLAGS)" \\
	"\$(EXEFLAGS)" \$@ "\$<" \\
	"\$(${sulname}OBJS) \$(${sulname}LINK)"

EOF
      
   fi
else
   echo "Error: Invalid file ($cxxfile)."
fi

